// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVr7gpcuie65_HxLXSHjHXbZKaOmYIcis',
    appId: '1:939008307536:web:e671808a28ff0b3ffc3c55',
    messagingSenderId: '939008307536',
    projectId: 'chat-f5bcd',
    authDomain: 'chat-f5bcd.firebaseapp.com',
    storageBucket: 'chat-f5bcd.appspot.com',
    measurementId: 'G-N4GFH98CFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiGLTydkpYctn65D3fhagfZK4XBPPB1wo',
    appId: '1:939008307536:android:bc4c6ed5120bdf8afc3c55',
    messagingSenderId: '939008307536',
    projectId: 'chat-f5bcd',
    storageBucket: 'chat-f5bcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzROj3bj95URfxkuePmq6mPXtOOZOMqM0',
    appId: '1:939008307536:ios:95376d2d55e9c12afc3c55',
    messagingSenderId: '939008307536',
    projectId: 'chat-f5bcd',
    storageBucket: 'chat-f5bcd.appspot.com',
    iosClientId: '939008307536-5nd30o8j7inoimkbhbr5hvrecb44s440.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
